using System.Collections; using System.Collections.Generic; using UnityEngine; using System.Reflection; using System; using Random = UnityEngine.Random;  public class MineSpawner : MonoBehaviour {     public static MineSpawner instance;     public int MineCounter;     public float spawnDelay;     public float timer;     public float spawnDelay1;     public float timer1;     public GameObject mine1;     public bool stopSpawning = false;     public int zNumber;     public int repeat;     public int a;     public int b;     public int c;     public int d;     public int e;     public int f;     public int g;     public int h;     public int i;     public int j;     public int k;     public int l;
    public int spawnCounter;

    // Start is called before the first frame update
    void Start()     {          instance = this;         InvokeRepeating("SpawnObject", timer, spawnDelay);     }

     public void SpawnObject()     {         PongBall pongBall = GetComponent<PongBall>();          zNumber = Random.Range(-26, 27);         if (zNumber == -2|| zNumber == -1 || zNumber == 0 || zNumber == 1 || zNumber == 2)
        {
            zNumber= Random.Range(-26, 27);
        }         if (zNumber == a || zNumber == a - 1 || zNumber == a + 1)
        {
            zNumber = Random.Range(-26, 27);
        }         if (zNumber == b || zNumber == b - 1 || zNumber == b + 1)         {             zNumber = Random.Range(-26, 27);         }         if (zNumber == c || zNumber == c - 1 || zNumber == c + 1)         {             zNumber = Random.Range(-26, 27);         }         if (zNumber == d || zNumber == d - 1 || zNumber == d + 1)         {             zNumber = Random.Range(-26, 27);         }         if (zNumber == e || zNumber == e - 1 || zNumber == e + 1)         {             zNumber = Random.Range(-26, 27);         }         if (zNumber == f || zNumber == f - 1 || zNumber == f + 1)         {             zNumber = Random.Range(-26, 27);         }         if (zNumber == g || zNumber == g - 1 || zNumber == g + 1)         {             zNumber = Random.Range(-26, 27);         }         if (zNumber == h || zNumber == h - 1 || zNumber == h + 1)         {             zNumber = Random.Range(-26, 27);         }         if (zNumber == i || zNumber == i - 1 || zNumber == i + 1)         {             zNumber = Random.Range(-26, 27);         }         if (zNumber == j || zNumber == j - 1 || zNumber == j + 1)         {             zNumber = Random.Range(-26, 27);         }         if (zNumber == k || zNumber == k - 1 || zNumber == k + 1)         {             zNumber = Random.Range(-26, 27);         }         if (zNumber == l || zNumber == l - 1 || zNumber == l + 1)         {             zNumber = Random.Range(-26, 27);         }         if (spawnCounter == 0)
        {
            a = zNumber;
        }         if (spawnCounter == 1)         {             b = zNumber;         }         if (spawnCounter == 2)         {             c = zNumber;         }         if (spawnCounter == 3)         {             d = zNumber;         }         if (spawnCounter == 4)         {             e = zNumber;         }         if (spawnCounter == 5)         {             f = zNumber;         }         if (spawnCounter == 6)         {             g = zNumber;         }         if (spawnCounter == 7)         {             h = zNumber;         }         if (spawnCounter == 8)         {             i = zNumber;         }         if (spawnCounter == 9)         {             j = zNumber;         }         if (spawnCounter == 10)         {             k = zNumber;         }         if (spawnCounter == 11)         {             l = zNumber;             spawnCounter = 0;         }         transform.position = new Vector3( 0f, 0.82f, zNumber);         MineCounter = MineCounter + 1;          Instantiate(mine1, transform.position, transform.rotation);         spawnCounter = spawnCounter + 1;     }     private void Update()     {         if (MineCounter >= 5)         {             CancelInvoke("SpawnObject");             repeat = repeat + 1;         }          if(MineCounter <5 && repeat>0)         {             InvokeRepeating("SpawnObject", timer1, spawnDelay1);
            repeat = 0;         }     } } 